### PR TITLE
Add Document#cache_key for ActionView::Helpers::CacheHelper#cache

### PR DESCRIPTION
**Pull request by seivan**
This is usually called inside a cache() block on the view
<% cache(@profile) do %>

Will append different values on the plural model name if
new_record?    - will append /new
updated_at       - will append /id-updated_at.to_s(:number)
No timestamps - will append /id

### CODE REVIEW

**Comment by seivan** [comment]
I was wondering if the user would like to user other time fields as the cache key in which case there are two solutions:

* Pass an array with other Time fields and pick max()
* Leave it as it is, and let the user override cache_key themselves with whatever they want.

**Comment by nviennot** [comment]
Hi Seivan :)

Few comments:

1) Let's put that method in the `PrimaryKey` module.

2) Let's use `self.class.table_name` instead of `self.class.model_name.cache_key`. Since the table name is configurable, two model with the same id with different table_names should not share the same cache key

3) `updated_at.to_i` and `updated_at.utc.to_i`yield the same values, so you can remove `.utc`.

4) The distinction with `.new_record?` doesn't seem useful as we always have an id, even before the record is created (unlike ActiveRecord).

5) The convention for key separator is to use `:` in NoBrainer, as it seems to be the standard with redis.

So how about we use something like this:

```ruby
  def cache_key
    if updated_at = _read_attribute(:updated_at)
      "#{self.class.table_name}:#{pk_value}-#{updated_at.to_i}"
    else
      "#{self.class.table_name}:#{pk_value}"
    end
  end
```

Thanks for the pull request :)

Nico

**Comment by seivan** [comment]
@nviennot Amazing feedback, I appreciate it. I'll update shortly!

**Comment by nviennot** [comment]
I've ended up implementing the feature with little code, but I've maintained your authorship on the commit due to the initial work :)

Thanks,
Nico.

**Comment by seivan** [comment]
@nviennot No worries, but uhm I actually found a couple of things about your feedback that isn't valid. You're still interested, or we're done here?

**Comment by nviennot** [comment]
Yes please!!
Btw, if you look at the implementation, it's different from my initial feedback.

**Pull request closed without merging**
