### PR TITLE
Suport Reflections

### PR DESCRIPTION
**Pull request by brunoalano**
This pull request aims to support Simple Form Associations, since they're based on ActiveModel reflections.

### CODE REVIEW

**Comment by brazenbraden** [comment]
This is a feature I would really like to be able to use. What is the status on it? Currently, it throws the error:

**/lib/no_brainer/autoload.rb:24:in `const_get': cannot load such file -- no_brainer/document/reflections (LoadError)**

**Comment by nviennot** [comment]
Hi there :)

It would be preferable to put this reflection compatibility layer in a separate gem, as its use case are limited (just for simple form?).

Also, if you try to use nested models with simple_form, it's not going to work well with NoBrainer. From what I'm seeing here: https://github.com/plataformatec/simple_form/wiki/Nested-Models, simple_form relies on accept_nested_attributes, which won't be implemented with NoBrainer (or in a separate gem).

The reason why this will not be implemented is due to the lack of atomicity of the save operation since there are no transactions

**Comment by brazenbraden** [comment]
In that case, I better learn how to start writing gems! :P 

Yea I saw the other feature request asking for accept_nested_attributes_for and your response to that. Totally understood.

Thanks for the heads up.

**Comment by nviennot** [comment]
Awesome!

**Pull request closed without merging**
