### PR TITLE
Prototype of polymorphic associations

### PR DESCRIPTION
**Pull request by mbrock**
This implements polymorphic associations with the same keyword options as used by ActiveRecord and Mongoid.

I don't know if this is what we want for NoBrainer, but it's a start!

### CODE REVIEW

**Comment by mbrock** [comment]
I'm mostly opening this pull request to get feedback. I've been working on it for half a day and now I'm tired and need to go home!

As far as missing stuff goes:

- I think there should be more checking of incompatible options, etc.
- I think there is something missing related to mutation, `changed?` methods, etc.

Also, maybe we should allow custom naming of the `<x>_id` and `<x>_type` fields.

**Comment by nviennot** [comment]
A couple of quick notes:
1) We want to subclass BelongsTo into a BelongsToPolymorphic class (like the subclassing of the has_one association)
2) has many through must be able to go through these belongs to associations. The good news is that it leverages the eager loading code. The bad news is that the method `target_type` that you wanted the other day will no longer be working.
3) Eager loading have to be supported. This will have to change a bit since we might have to query different tables

You can do 1) no problem, I'll drop some more comments later.
I'll drop some comments later so you won't have the temptation to read them since you are already tired :)

Thank you Mikael :)

**Comment by nviennot** [comment]
Also, don't comment on your commit, but commit on the PR: https://github.com/nviennot/nobrainer/pull/116/files

**Comment by nviennot** [comment]
(and also :scope won't work on has_many :through association that encounter a polymorphic association)

**Comment by mbrock** [comment]
Okay, I gave your first point a shot. Hm, I force pushed it which makes the history a bit confusing, maybe I should work with regular pushes and then consolidate them later.

**Comment by nviennot** [comment]
I though about it a little more. Here are my thoughts.
1) We don't do eager loading on polymorphic associations due to code complexity.
2) That means that we don't support has_many through on polymorphic belongs_to
That means that if we want to implement the polymorphic feature, we have to keep the it to a bare minimum.

Note that Sequel does not implement polymorphic associations because they are complex, and throw away some guarantees it tries to enforce (we started to see this with "Cannot statically determine..." errors):
http://sequel.jeremyevans.net/rdoc/files/doc/advanced_associations_rdoc.html#label-Polymorphic+Associations

Let's back up a little bit. What's the benefit of having polymorphic associations? Maybe it's not such a great feature after all?
So what's a reasonable usecase for polymorphic associations?

**Comment by mbrock** [comment]
The Sequel authors may have a point.

I don't have a burning need for polymorphic associations myself, but the `rails_admin` test app uses them, and I saw them mentioned on the roadmap, so I figured I would give it a shot, partly just to familiarize myself with the NoBrainer codebase.

However, they do seem pretty convenient. The basic usecase is having one model belong to several others.

The classic example seems to be having a `Comment` model that can be attached to many types of other entities. I can easily imagine other similar cases, like `Tag`s and "metadata" of various kinds. Another example I've seen is having an `Address` model that can belong to a `Person` or a `Company`.

I would agree that if the feature were included in NoBrainer, it would be nice to keep it as simple as possible. My current code is rather simple. I think that if we exclude eager loading, then polymorphic associations are not necessarily (as the Sequel authors state) "much more complicated."

And I don't think the Sequel authors' point about breaking referential integrity applies for RethinkDB. :smile:

**Comment by nviennot** [comment]
For the tags feature, I would this this is better:

```ruby
module Taggable
  extend ActiveSupport::Concern
  included do
    field :tags, :type => Array, default => [], :index => :multi
  end
end

class Post
  include NoBrainer::Document
  include Taggable
end
```

For the address feature, I would do the same thing, and put all the related logic in a module.
The address feature is also a prime candidate for embedded documents. We don't have support for at the moment, but it would look like this:

```ruby
class Address
  include NoBrainer::EmbeddedDocument

  field :street
  field :zipcode
  field :country
end

class User
  include NoBrainer::Document
  field :shipping_address, :type => Address
  field :billing_address, :type => Address
end

class Company
  include NoBrainer::Document
  field :address, :type => Address
end
```

The address usecase falls appart with the polymorphic stuff when it comes to shipping/billing addresses.

I'm still not convinced that we should go ahead with the polymorphic associations

**Comment by mbrock** [comment]
Me neither. I hadn't thought about the relation to embedded documents.

If addresses are entities in your system, as opposed to values—such that you would want to list all registered addresses, update them, reuse them, and so on—then I think polymorphic associations could be useful.

However, since my only reason to want them is to make the `rails_admin` tests pass, I don't want to argue for them too vigorously! I think I can rather easily change the test suite to use two different `Comment` entities in the NoBrainer variant.

**Comment by nviennot** [comment]
> If addresses are entities in your system, as opposed to values—such that you would want to list all registered addresses, update them, reuse them, and so on—then I think polymorphic associations could be useful.

How would you have a billing and shipping address at the same time with polymorphic associations?
I would argue that the only way is to put the foreign keys on the user model. That is, `User.belongs_to :shipping_address, :class_name => :Address` and `User.belongs_to :billing_address, :class_name => :Address` -- you wouldn't need polymorphic associations.

I can see that listing all registered addresses and updating them is useful (e.g. performing migrations on the address model for example). But this is where relational databases shine, because you get to normalize your data really well. But with a document database, it might be more interesting to use embedded hashes in some places. It's like the tags example. In a traditional relational DB, you would have a separate table called 'tags' with a bunch of foreign keys and everything. With a document DB, it makes a lot more sense to maintain an array of strings.
Having said that, if one does a migration on the Address class (embedded document), then it turns into a really unpleasant experience. So maybe embedded documents are not necessarily the answer.

Since it's for rails_admin and you don't *need* it, maybe it's best to not support polymorphic associations for now, and let this one sit for a while.

Regardless, thank you very much for having spend some time writing code, and tests :)
This is greatly appreciated :)

**Pull request closed without merging**
